name: build

permissions:
  contents: write

on:
  push:
    tags:
      # Match any new tag
      - "*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: "scry-linux-amd64"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "scry-win-amd64.exe"
            platform: "windows/amd64"
            os: "windows-latest"
          - name: "scry"
            platform: "darwin/universal"
            os: "macos-latest"

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: "^1.23"
          node-version: "22.x"

      # workaround for mac builds breaking with name changes
      - name: Prepackaging
        if: runner.os == 'macOS' && startsWith(github.ref, 'refs/tags/')
        shell: bash
        working-directory: .
        run: |
          mv ./build/bin/${{ matrix.build.name }}.app.zip ./build/bin/${{ matrix.build.name }}-macos-darwin.app.zip

      - name: Package
        uses: actions/upload-artifact@v4
        with:
          name: app-build-${{runner.os}}
          path: |
            */bin/
            *\bin\*

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            */bin/*